import { Component, output } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { FormBuilder } from '@angular/forms';
import { TaskForm } from '../task/task.form';
import { TaskModel } from '../task/task.model';
import { TaskPriority, TaskStatus } from '../enums';
import { SelectListItem } from '../shared/models/selectListItem';
import { IdService } from '../service/id.service';
import { TodoWebApi } from '../service/todoWebApi.service';

declare var bootstrap: any;

@Component({
  imports: [
    ReactiveFormsModule
  ],
  selector: 'app-task',
  styleUrl: './task.css',
  templateUrl: './task.html',
})
export class Task {

  form: TaskForm;
  saveError: string = '';
  taskSaved = output<void>();
  taskPriority: SelectListItem[] = Object.values(TaskPriority).map((value) => ({
    value,
    text: value,
  }));
  taskStatus: SelectListItem[] = Object.values(TaskStatus).map((value) => ({
    value,
    text: value,
  }));

  constructor(private fb: FormBuilder, private idService: IdService, private todoWebApiService: TodoWebApi) {
    this.form = new TaskForm(this.fb);
  }

  ngOnInit() {
    this.resetForm();
  }

  private resetForm() {
    this.form.reset();
    this.form.setData({
      id: 0,
      task: '',
      description: '',
      priority: TaskPriority.Low,
      status: TaskStatus.New,
      dueDate: new Date()
    } as TaskModel);
  }

  save() {
    if(this.form.valid) {
      const taskData = this.getFormData();
      this.saveError = '';
      this.todoWebApiService.addTask(taskData).subscribe({
        next: () => {
          const modalElement = document.getElementById('addTaskModal');
          if (modalElement) {
            const modalInstance = bootstrap.Modal.getInstance(modalElement);
            modalInstance?.hide();
          }
          this.resetForm();
          this.taskSaved.emit();
        },
        error: error => {
          this.saveError = error instanceof Error ? error.message : 'Unable to save the task.';
        },
      });
    }
    else {
      this.form.markAllAsTouched();
    }
  }

  cancel() {
    this.saveError = '';
    this.resetForm();
  }

  getFormData(): TaskModel{
    const data = this.form.getRawValue();

    return {
      id: this.idService.getNextId(), // For testing purpose, the ID would be generated by the backend.
      task: data.task ?? '',
      description: data.description ?? '',
      priority: data.priority ?? 0,
      status: data.status ?? 0,
      dueDate: data.dueDate
        ? this.toDate(data.dueDate)
        : new Date()
    } as TaskModel;
  }

  private toDate(date: string): Date {
    const [year, month, day] = date.split('-').map(Number);
    return new Date(year, month - 1, day);
  }
}
